#
# lint and test the code on push
# to any branch except master
#
# push-to-master is disabled; any push to master must have passed lint+test
#

name: lint+test
on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - "**"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: black
      uses: lgeiger/black-action@master
      with:
        args: .

    - name: check for modifications
      id: git-check
      run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

    - name: push changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name github-actions
        git config --global user.email '${GITHUB_ACTOR@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout `basename $GITHUB_REF`
        git commit -am "Automated changes"
        git push origin HEAD:`basename $GITHUB_REF`

  test:
    runs-on: ubuntu-latest

    needs:
    - format

    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install pyblaise
      run: pip install .

    - name: pytest
      run: |
        pip install -q pytest pytest-cov
        pytest --cov=pyblaise
